user_input_path: /Users/guantianyun/Desktop/上架交付文档(203数据平台14个机柜)-20220714.xlsx
sheet_rack_view: Rack_View
sheet_switch_connections: Switch Connections

result_file_path: /Users/guantianyun/Desktop/结果输出V1.0.xlsx